### ISSUE TITLE
Link in READ.ME doesnt work

### ISSUE THREAD

**Issue by jakub-ruzicka** [kraxnet/dopis_online_client#5]

**Comment by jtheserg** [comment]
I think that it should be "[https://online.postservis.cz/Download/DopisOnline/DopisOnlineUzivatelskaPrirucka.pdf](https://online.postservis.cz/Download/DopisOnline/DopisOnlineUzivatelskaPrirucka.pdf)", but I'm not sure.

**Comment by kubicek** [comment]
Fixed in 131dc27, thanks
